name: wired_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aws-c-auth=0.7.18=he0b1f16_0
  - aws-c-cal=0.6.11=heb1d5e4_0
  - aws-c-common=0.9.15=hd590300_0
  - aws-c-compression=0.2.18=hce8ee76_3
  - aws-c-event-stream=0.4.2=h01f5eca_8
  - aws-c-http=0.8.1=hdb68c23_10
  - aws-c-io=0.14.7=hbfbeace_6
  - aws-c-mqtt=0.10.4=h50844eb_0
  - aws-c-s3=0.5.7=h6be9164_2
  - aws-c-sdkutils=0.1.15=hce8ee76_3
  - aws-checksums=0.1.18=hce8ee76_3
  - aws-crt-cpp=0.26.8=h2150271_2
  - aws-sdk-cpp=1.11.267=hddb5a97_7
  - blas=1.0=openblas
  - blosc=1.21.5=hc2324a3_1
  - bottleneck=1.3.8=py39h44dd56e_0
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py39h06a4308_0
  - cftime=1.6.3=py39h44dd56e_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py39h7633fee_0
  - cytoolz=0.12.3=py39hd1e30aa_0
  - dask=2024.5.0=pyhd8ed1ab_0
  - dask-core=2024.5.0=pyhd8ed1ab_0
  - dask-expr=1.1.0=pyhd8ed1ab_0
  - distributed=2024.5.0=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.3.1=pyhca7485f_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.7.0=hed5481d_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.3=nompi_h4f84152_101
  - icu=73.2=h59595ed_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarrow=15.0.2=hefa796f_6_cpu
  - libarrow-acero=15.0.2=hbabe93e_6_cpu
  - libarrow-dataset=15.0.2=hbabe93e_6_cpu
  - libarrow-flight=15.0.2=hc4f8a93_6_cpu
  - libarrow-flight-sql=15.0.2=he4f5ca8_6_cpu
  - libarrow-gandiva=15.0.2=hc1954e9_6_cpu
  - libarrow-substrait=15.0.2=he4f5ca8_6_cpu
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.7.1=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_6
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libgomp=13.2.0=h77fa898_6
  - libgoogle-cloud=2.23.0=h9be4e54_1
  - libgoogle-cloud-storage=2.23.0=hc7a4891_1
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - libllvm16=16.0.6=hb3ce162_3
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libparquet=15.0.2=hacf5a1f_6_cpu
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h29866fb_1
  - libutf8proc=2.8.0=h166bdaf_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.12.6=h232c23b_2
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py39h79d96da_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - msgpack-python=1.0.7=py39h7633fee_0
  - ncurses=6.4=h6a678d5_0
  - netcdf4=1.6.5=nompi_py39h4282601_100
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.0=hd590300_0
  - orc=2.0.0=h17fec99_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py39hddac248_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pillow=10.0.1=py39h444a776_1
  - pip=23.3.1=py39h06a4308_0
  - psutil=5.9.8=py39hd1e30aa_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=15.0.2=py39h38d04b8_6_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.19=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - rdma-core=51.0=hd3aeb46_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - s2n=1.4.12=h06160fa_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hdb0a2a9_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py39hd1e30aa_0
  - tzdata=2024a=h04d1e81_0
  - ucx=1.15.0=ha691c75_8
  - wheel=0.43.0=py39h06a4308_0
  - xarray=2024.3.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiofiles==22.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - altair==5.3.0
      - ansi2html==1.9.2
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asteval==0.9.33
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.8.2
      - bokeh==3.3.4
      - boto3==1.34.132
      - botocore==1.34.132
      - branca==0.7.2
      - cartopy==0.23.0
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - colorcet==3.1.0
      - comm==0.2.2
      - cramjam==2.8.3
      - cycler==0.12.1
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datashader==0.16.2
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - entrypoints==0.4
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fastparquet==2024.5.0
      - flask==3.0.3
      - folium==0.17.0
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozendict==2.4.4
      - frozenlist==1.4.1
      - geodatasets==2023.12.0
      - geopandas==1.0.0
      - geoviews==1.11.1
      - greenlet==3.0.3
      - h11==0.14.0
      - h5py==3.11.0
      - hdf5plugin==4.4.0
      - holoviews==1.19.0
      - html5lib==1.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - hvplot==0.10.0
      - idna==3.7
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - intake==2.0.5
      - ipykernel==6.29.4
      - ipysheet==0.7.0
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.3
      - ipywidgets-bokeh==1.6.0
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-bokeh==4.0.5
      - jupyter-client==7.4.9
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-resource-usage==0.7.2
      - jupyter-server==2.14.0
      - jupyter-server-fileid==0.9.2
      - jupyter-server-proxy==4.2.0
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.27.1
      - jupyterlab-system-monitor==0.8.0
      - jupyterlab-topbar==0.6.1
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lmfit==1.3.1
      - lxml==5.2.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - more-itertools==10.3.0
      - mplcursors==0.5.3
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multitasking==0.0.11
      - nbclassic==1.1.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nbgitpuller==1.2.1
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nexpy==1.0.9
      - nexusformat==1.0.6
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numcodecs==0.12.1
      - numexpr==2.10.1
      - opencv-python==4.9.0.80
      - openvisus==2.2.131
      - openvisuspy==1.0.66
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - panel==1.3.8
      - param==2.1.0
      - parso==0.8.4
      - patsy==0.5.6
      - peewee==3.17.5
      - pexpect==4.9.0
      - platformdirs==4.2.1
      - plotly==5.22.0
      - pooch==1.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pyct==0.5.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - pylatexenc==2.10
      - pyogrio==0.9.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyshp==2.3.1
      - python-json-logger==2.0.7
      - pyvista==0.43.10
      - pyviz-comms==2.3.2
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.31.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - s3transfer==0.10.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.0
      - scipy==1.13.0
      - scooby==0.10.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shapely==2.0.4
      - simpervisor==1.0.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - tenacity==8.4.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.6.18
      - tinycss2==1.3.0
      - tomli==2.0.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - trame==3.6.3
      - trame-client==3.2.0
      - trame-server==3.0.2
      - trame-vtk==2.8.9
      - trame-vuetify==2.6.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - uc-micro-py==1.0.3
      - uncertainties==3.2.1
      - uri-template==1.3.0
      - urllib3==1.26.19
      - vega-datasets==0.9.0
      - vtk==9.3.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - wget==3.2
      - widgetsnbextension==4.0.11
      - wslink==2.1.1
      - xlrd==2.0.1
      - xmltodict==0.13.0
      - y-py==0.6.2
      - yarl==1.9.4
      - yfinance==0.2.40
      - ypy-websocket==0.8.4
      - zarr==2.18.2
prefix: /home/collab/arleth/miniconda3/envs/wired_env
